### ISSUE TITLE
How to define a route?

### ISSUE THREAD

**Issue by aripka-pivotal** [xebialabs-community/xld-cloud-foundry-plugin#4]
Working on using this plugin to deploy to Pivotal Cloud Foundry.  I was able to create and application package and deploy an application.  However it does not have a mapped route, and I assumed it would create one with the supplied hostname and existing domain name.

Do you have to predefine the route?  If so how is that accomplished.

**Comment by jdewinne** [comment]
Hey,

Did you add a route to the `cf.War`?
See also the [synthetic.xml](https://github.com/xebialabs-community/xld-cloud-foundry-plugin/blob/master/src/main/resources/synthetic.xml#L65) for the type definition.

Regards,
Joris

**Comment by aripka-pivotal** [comment]
Do you add the route to the cf.War type when adding the file?  I could not find a location to do so there.  Or is this configured at some other point in the creation of the application package?

**Comment by jdewinne** [comment]
A `cf.Route` is an [embedded CI](https://github.com/xebialabs-community/xld-cloud-foundry-plugin/blob/master/src/main/resources/synthetic.xml#L87). This means it is part of another CI. So if you right click on a `cf.War`, you should be able to add a `cf.Route`

**Comment by aripka-pivotal** [comment]
Note confusion on my end caused buy unfamiliarity with client's use of flash ui to create packages in deployments view.  On.ce we were using repository view adding a route was as described.  Closing issue as solved
